name: workflow to analyze and fix bash part of the project

on: [push, pull_request, workflow_dispatch]

jobs:
    shellcheck:
        name: shell check
        runs-on: ubuntu-latest

        steps: 
            - name: checkout
              uses: actions/checkout@v4

            - name: perform check
              run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)
