name: Python syntax check

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  

      - name: install black
        run: pip install black

      - name: run black linter
        run: black . --verbose

      - name: check if there are any changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR with fixes if there are any
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "style: auto-format with black"
          title: "linting using black"
          branch: lint-fixes/${{ github.run_id }}
