name: Python syntax check

on: [push, pull_request, workflow_dispatch]

permissions:
    contents: "write"

jobs:
    lint:
        runs-on: ubuntu-latest
        
        steps:
            - name: check out repo
              uses: actions/checkout@v4

            - name: perform-black-lint-check
              uses: psf/black@stable
              with:
                options: "--verbose"
            
            - name: commit changes made
              run: |
                git config user.name "Black-lint"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                
                git add .
                
                # commit if there are chanes
                if ! git diff --cached --quiet; then
                git commit -m "lint: auto-format with Black"
                git push
                else
                echo "No changes to commit."
                fi
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


            