name: Python syntax check

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        
        steps:
            - name: check out repo
              uses: actions/checkout@v4

            - name: perform-black-lint-check
              uses: psf/black@stable
              with:
                options: "--verbose"

            